# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ictuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ictuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='ictuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='IctUser',
        ),
    ]
