# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 19:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='sign',
            name='users',
        ),
        migrations.AddField(
            model_name='sign',
            name='command',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign',
            name='isface',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sign',
            name='isverify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signeduser',
            name='sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signedusers', to='interact.Sign'),
        ),
        migrations.AddField(
            model_name='signeduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signedrecord', to=settings.AUTH_USER_MODEL),
        ),
    ]
