# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0002_auto_20160603_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timeL', models.DateTimeField()),
                ('timeR', models.DateTimeField()),
                ('caption', models.TextField(default='')),
                ('ischoose', models.BooleanField(default=False)),
                ('sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='interact.Sign')),
            ],
        ),
        migrations.CreateModel(
            name='VoteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('num', models.IntegerField(default=0)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteitems', to='interact.Vote')),
            ],
        ),
    ]
