# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 12:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0002_auto_20160523_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='hold_users',
            field=models.ManyToManyField(related_name='activities_held', to=settings.AUTH_USER_MODEL),
        ),
    ]
